---
version: 2
jobs:
    build-armhf-buster:
        machine: true
        environment:
        - OCPN_TARGET=buster-armhf
        - DOCKER_IMAGE=canne/raspbian-buster:plugin_build_tooling_current
        - BUILD_FLAGS=-j3
        steps:
        - checkout
        - run: chmod a+x ./.circleci/*.sh
        - run:
            command: .circleci/circleci-build-raspbian-armhf.sh
            no_output_timeout: 30m
        - run: .circleci/cloudsmith-upload.sh
    build-focal:
        docker:
        - image: circleci/buildpack-deps:focal-scm
        environment:
        - OCPN_TARGET:  focal
        steps:
        - checkout
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ focal main"
            | sudo tee -a /etc/apt/sources.list
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ focal-updates main"
            | sudo tee -a /etc/apt/sources.list
        - run: cat /etc/apt/sources.list
        - run: chmod a+x .circleci/*.sh
        - run: .circleci/circleci-build-debian.sh
        - run: .circleci/cloudsmith-upload.sh
    build-flatpak:
        machine:
            image: circleci/classic:201808-01
        environment:
        - OCPN_TARGET:  flatpak
        - CLOUDSMITH_PKG_EXT: gz
        steps:
        - checkout
        - run: chmod a+x .circleci/*.sh
        - run: bash .circleci/circleci-build-flatpak.sh
        - run: bash .circleci/cloudsmith-upload.sh
    build-mingw:
        docker:
        - image: fedora:29
        environment:
        - OCPN_TARGET:  mingw
        - CLOUDSMITH_PKG_EXT: exe
        steps:
        - run: su -c "dnf install -q -y git openssh-clients openssh-server"
        - checkout
        - run: chmod a+x .circleci/*.sh
        - run: bash .circleci/circleci-build-mingw.sh
        - run: bash .circleci/cloudsmith-upload.sh
workflows:
    version: 2
    build_all:
        jobs:
        - build-armhf-buster:
            filters:
                branches:
                    ignore:
                    - devel
                    - tmp
                tags:
                    only: /.*/
        - build-focal:
            filters:
                branches:
                    ignore:
                    - devel
                    - tmp
                tags:
                    only: /.*/
        - build-flatpak:
            filters:
                branches:
                    ignore:
                    - devel
                    - tmp
                tags:
                    only: /.*/
        - build-mingw:
            filters:
                branches:
                    ignore:
                    - devel
                    - tmp
                tags:
                    only: /.*/

