---
version: 2.1

orbs:
    cloudsmith: cloudsmith/cloudsmith@1.0.4

jobs:
    publish:
        steps:
        - checkout
        - cloudsmith/ensure-api-key
        - cloudsmith/install-cli
        - docker:
            - image: circleci/buildpack-deps:focal-scm
            - run: >
                echo "deb-src http://us.archive.ubuntu.com/ubuntu/ focal main"
                | sudo tee -a /etc/apt/sources.list
            - run: >
                echo "deb-src http://us.archive.ubuntu.com/ubuntu/ focal-updates main"
                | sudo tee -a /etc/apt/sources.list
            - run: cat /etc/apt/sources.list
            - run: chmod a+x .circleci/*.sh
            - run: .circleci/circleci-build-debian.sh
        - cloudsmith/publish:
            cloudsmith-repository: canne/DashT
            package-format: linux
            package-path: build/dashboard_tactics_pi_1.98.*

workflows:
    cloudsmith-publish:
        jobs:
            -publish
