---
version: 2
jobs:
    build-focal:
        docker:
        - image: circleci/buildpack-deps:focal-scm
        environment:
        - OCPN_TARGET:  focal
        steps:
        - checkout
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ focal main"
            | sudo tee -a /etc/apt/sources.list
        - run: >
            echo "deb-src http://us.archive.ubuntu.com/ubuntu/ focal-updates main"
            | sudo tee -a /etc/apt/sources.list
        - run: cat /etc/apt/sources.list
        - run: chmod a+x .circleci/*.sh
        - run: .circleci/circleci-build-debian.sh
        - run: .circleci/cloudsmith-upload.sh
workflows:
    version: 2
    build_all:
        jobs:
        - build-focal:
            filters:
                branches:
                    ignore:
                    - devel
                    - tmp
                tags:
                    only: /.*/
