# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ dev200 ]
    paths:
      - '**.js'
      - '**.ts'
      - '**.scss'
      - '**.html'
  pull_request:
    branches: [ pr200 ]
    paths:
      - '**.js'
      - '**.ts'
      - '**.scss'
      - '**.html'

jobs:
  build:

    strategy:
      matrix:
        js-instruments: ['./instrujs/racedashmark']

    runs-on: ubuntu-latest
    env:
      working-directory: {{ matrix.js-instruments }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
      working-directory: ${{ env.working-directory }}
    - run: npm run build --if-present
      working-directory: ${{ env.working-directory }}
#    - run: npm test
      env:
        CI: true
